id: ch.chmed.emediplan
canonical: http://chmed.emediplan.ch/fhir
name: CHMED
status: active
version: 2.2.0
date: 2023-08-23
fhirVersion: 4.0.1
copyrightYear: 2017+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: IG eMediplan
  url: http://www.emediplan.ch

parameters:
  apply-publisher: false
  allow-extensible-warnings: true

title: eMediplan CHMED Implementation Guide
description: FHIR IG for eMediplan
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CHE

dependencies:
  ch.fhir.ig.ch-emed: 4.0.0-ballot
  ch.fhir.ig.ch-core: 4.0.0-ballot


# ----- Define IG tabs (page content) -----
menu:
  Home: index.html
  Documents: documents.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Dosage: dosage.html
  Artifacts: artifacts.html

# ----- Define own titles (default: IG Publisher generates titles) -----
pages:
  index.md:
    title: Home
  documents.md:
    title: FHIR Documents
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology
  dosage.md:
    title: Dosage
  changelog.md:
    title: Changelog