id: ch.chmed.emediplan
canonical: http://chmed.emediplan.ch/fhir
name: CHMED
status: active
version: 3.0.0
date: 2022-02-18
fhirVersion: 4.0.1
copyrightYear: 2017+
releaseLabel: CI Build
publisher:
  name: IG eMediplan
  url: http://www.emediplan.ch

parameters:
  apply-publisher: false

title: eMediplan CHMED Implementation Guide
description: FHIR IG for eMediplan
license: CC-BY-SA-4.0
copyright: CC-BY-SA-4.0
jurisdiction: urn:iso:std:iso:3166#CHE

dependencies:
  ch.fhir.ig.ch-emed: 2.0.0
  ch.fhir.ig.ch-core: 2.0.0


# ----- Define IG tabs (page content) -----
menu:
  Home: index.html
  Introduction: intro.html
  Profiles: profiles.html
  Private Fields: privatefields.html
  Terminology: terminology.html
  Dosage: dosage.html
  Artifacts: artifacts.html

# ----- Define own titles (default: IG Publisher generates titles) -----
pages:
  index.md:
    title: Home
  intro.md:
    title: Introduction
  profiles.md:
    title: Profiles
  privatefields.md:
    title: Private Fields
  terminology.md:
    title: Terminology
  dosage.md:
    title: Dosage
  changelog.md:
    title: Change Log