curl -i -X PUT -H "Content-Type:text/xml" --data @./Composition/chmed16af-mp-composition-s01.xml  http://fhir3.healthintersections.com.au/open/Composition/chmed16af-mp-composition-s01
curl -i -X PUT -H "Content-Type:text/xml" --data @./Condition/chmed16af-mp-condition-s01-1.xml  http://fhir3.healthintersections.com.au/open/Condition/chmed16af-mp-condition-s01-1
curl -i -X PUT -H "Content-Type:text/xml" --data @./Condition/chmed16af-mp-condition-s01-2.xml  http://fhir3.healthintersections.com.au/open/Condition/chmed16af-mp-condition-s01-2
curl -i -X PUT -H "Content-Type:text/xml" --data @./Condition/chmed16af-mp-condition-s01-3.xml  http://fhir3.healthintersections.com.au/open/Condition/chmed16af-mp-condition-s01-3
curl -i -X PUT -H "Content-Type:text/xml" --data @./Condition/chmed16af-mp-condition-s01-4.xml  http://fhir3.healthintersections.com.au/open/Condition/chmed16af-mp-condition-s01-4
curl -i -X PUT -H "Content-Type:text/xml" --data @./Condition/chmed16af-mp-condition-s01-5.xml  http://fhir3.healthintersections.com.au/open/Condition/chmed16af-mp-condition-s01-5
curl -i -X PUT -H "Content-Type:text/xml" --data @./Condition/chmed16af-mp-condition-s01-6.xml  http://fhir3.healthintersections.com.au/open/Condition/chmed16af-mp-condition-s01-6
curl -i -X PUT -H "Content-Type:text/xml" --data @./MedicationStatement/chmed16af-mp-medicationstatement-s01-1.xml  http://fhir3.healthintersections.com.au/open/MedicationStatement/chmed16af-mp-medicationstatement-s01-1
curl -i -X PUT -H "Content-Type:text/xml" --data @./MedicationStatement/chmed16af-mp-medicationstatement-s01-2.xml  http://fhir3.healthintersections.com.au/open/MedicationStatement/chmed16af-mp-medicationstatement-s01-2
curl -i -X PUT -H "Content-Type:text/xml" --data @./MedicationStatement/chmed16af-mp-medicationstatement-s01-3.xml  http://fhir3.healthintersections.com.au/open/MedicationStatement/chmed16af-mp-medicationstatement-s01-3
curl -i -X PUT -H "Content-Type:text/xml" --data @./MedicationStatement/chmed16af-mp-medicationstatement-s01-4.xml  http://fhir3.healthintersections.com.au/open/MedicationStatement/chmed16af-mp-medicationstatement-s01-4
curl -i -X PUT -H "Content-Type:text/xml" --data @./Observation/chmed16af-mp-observation-s01-bodyheight.xml  http://fhir3.healthintersections.com.au/open/Observation/chmed16af-mp-observation-s01-bodyheight
curl -i -X PUT -H "Content-Type:text/xml" --data @./Observation/chmed16af-mp-observation-s01-bodyweight.xml  http://fhir3.healthintersections.com.au/open/Observation/chmed16af-mp-observation-s01-bodyweight
curl -i -X PUT -H "Content-Type:text/xml" --data @./Observation/chmed16af-observation-s01-dateoflastmenustration.xml  http://fhir3.healthintersections.com.au/open/Observation/chmed16af-observation-s01-dateoflastmenustration
curl -i -X PUT -H "Content-Type:text/xml" --data @./Observation/chmed16af-observation-s01-prematurebaby.xml  http://fhir3.healthintersections.com.au/open/Observation/chmed16af-observation-s01-prematurebaby
curl -i -X PUT -H "Content-Type:text/xml" --data @./Observation/chmed16af-observation-s01-timeofgestation.xml  http://fhir3.healthintersections.com.au/open/Observation/chmed16af-observation-s01-timeofgestation
curl -i -X PUT -H "Content-Type:text/xml" --data @./Patient/chmed16af-mp-patient-s01.xml  http://fhir3.healthintersections.com.au/open/Patient/chmed16af-mp-patient-s01
curl -i -X PUT -H "Content-Type:text/xml" --data @./Practioner/chmed16af-practitioner-s01.xml http://fhir3.healthintersections.com.au/open/Practitioner/chmed16af-practitioner-s01

