curl -i -X PUT -H "Content-Type:text/xml" --data @./Composition/chmed16af-mp-composition-s01.xml  http://test.fhir.org/r3/Composition/chmed16af-mp-composition-s01
curl -i -X PUT -H "Content-Type:text/xml" --data @./Condition/chmed16af-mp-condition-s01-1.xml  http://test.fhir.org/r3/Condition/chmed16af-mp-condition-s01-1
curl -i -X PUT -H "Content-Type:text/xml" --data @./Condition/chmed16af-mp-condition-s01-2.xml  http://test.fhir.org/r3/Condition/chmed16af-mp-condition-s01-2
curl -i -X PUT -H "Content-Type:text/xml" --data @./Condition/chmed16af-mp-condition-s01-3.xml  http://test.fhir.org/r3/Condition/chmed16af-mp-condition-s01-3
curl -i -X PUT -H "Content-Type:text/xml" --data @./Condition/chmed16af-mp-condition-s01-4.xml  http://test.fhir.org/r3/Condition/chmed16af-mp-condition-s01-4
curl -i -X PUT -H "Content-Type:text/xml" --data @./Condition/chmed16af-mp-condition-s01-5.xml  http://test.fhir.org/r3/Condition/chmed16af-mp-condition-s01-5
curl -i -X PUT -H "Content-Type:text/xml" --data @./Condition/chmed16af-mp-condition-s01-6.xml  http://test.fhir.org/r3/Condition/chmed16af-mp-condition-s01-6
curl -i -X PUT -H "Content-Type:text/xml" --data @./MedicationStatement/chmed16af-mp-medicationstatement-s01-1.xml  http://test.fhir.org/r3/MedicationStatement/chmed16af-mp-medicationstatement-s01-1
curl -i -X PUT -H "Content-Type:text/xml" --data @./MedicationStatement/chmed16af-mp-medicationstatement-s01-2.xml  http://test.fhir.org/r3/MedicationStatement/chmed16af-mp-medicationstatement-s01-2
curl -i -X PUT -H "Content-Type:text/xml" --data @./MedicationStatement/chmed16af-mp-medicationstatement-s01-3.xml  http://test.fhir.org/r3/MedicationStatement/chmed16af-mp-medicationstatement-s01-3
curl -i -X PUT -H "Content-Type:text/xml" --data @./MedicationStatement/chmed16af-mp-medicationstatement-s01-4.xml  http://test.fhir.org/r3/MedicationStatement/chmed16af-mp-medicationstatement-s01-4
curl -i -X PUT -H "Content-Type:text/xml" --data @./Observation/chmed16af-mp-observation-s01-bodyheight.xml  http://test.fhir.org/r3/Observation/chmed16af-mp-observation-s01-bodyheight
curl -i -X PUT -H "Content-Type:text/xml" --data @./Observation/chmed16af-mp-observation-s01-bodyweight.xml  http://test.fhir.org/r3/Observation/chmed16af-mp-observation-s01-bodyweight
curl -i -X PUT -H "Content-Type:text/xml" --data @./Observation/chmed16af-observation-s01-dateoflastmenustration.xml  http://test.fhir.org/r3/Observation/chmed16af-observation-s01-dateoflastmenustration
curl -i -X PUT -H "Content-Type:text/xml" --data @./Observation/chmed16af-observation-s01-prematurebaby.xml  http://test.fhir.org/r3/Observation/chmed16af-observation-s01-prematurebaby
curl -i -X PUT -H "Content-Type:text/xml" --data @./Observation/chmed16af-observation-s01-timeofgestation.xml  http://test.fhir.org/r3/Observation/chmed16af-observation-s01-timeofgestation
curl -i -X PUT -H "Content-Type:text/xml" --data @./Patient/chmed16af-mp-patient-s01.xml  http://test.fhir.org/r3/Patient/chmed16af-mp-patient-s01
curl -i -X PUT -H "Content-Type:text/xml" --data @./Practitioner/chmed16af-practitioner-s01.xml http://test.fhir.org/r3/Practitioner/chmed16af-practitioner-s01

curl -i -X PUT -H "Content-Type:text/xml" --data @./Questionnaire/chmed16af-pmc-questionnaire.xml http://test.fhir.org/r3/Questionnaire/chmed16af-pmc-questionnaire
curl -i -X PUT -H "Content-Type:text/xml" --data @./QuestionnaireResponse/chmed16af-pmc-questionnaireresponse-s01.xml http://test.fhir.org/r3/QuestionnaireResponse/chmed16af-pmc-questionnaireresponse-s01
curl -i -X PUT -H "Content-Type:text/xml" --data @./Composition/chmed16af-pmc-composition-s01.xml http://test.fhir.org/r3/Composition/chmed16af-pmc-composition-s01
